### ISSUE TITLE
h$shutdownHaskellAndExit doesn't work in browser, resulting with infinite loops

### ISSUE THREAD

**Issue by osa1** [ghcjs/ghcjs#225]
Originally reported by trap_exit on IRC. Currently this bug is also blocking me.

This simple program:

``` haskell
main = error "hello"
```

Fails to terminate on Chrom/Chromium and probably others. It prints "If you can read this, shutdownHaskellAndExit did not exit." forever:

https://github.com/ghcjs/ghcjs-boot/blob/master/patches/base.patch#L395

The problem is caused by this function in `shims/pkg/base.js`:

``` haskell
function h$shutdownHaskellAndExit(code, fast) {
    if(typeof process !== 'undefined' && process.exit) {
        process.exit(code);
    } else if(typeof quit !== 'undefined') {
        quit(code);
    }
}
```

I think we need to somehow signal main loop to stop in this function, instead of forcing process to exit. 1) It may not possible to do that in browsers 2) even in node or other interpreters, stopping GHCJS main loop is different that terminating the whole app and I think what we should be doing is just stopping the GHCJS main loop and let rest of the program continue running.

**Comment by broma0** [comment]
I'm still experiencing this using Google Chrome and Chromium on the <a href="https://github.com/ghcjs/ghcjs/tree/89ea7b2ffdcf441fb215d0582570327b3aa7b1b6">latest commit</a> (as of writing this):

<pre>main = error "hello"</pre>

Was this fixed?

**Comment by luite** [comment]
I fixed this some time ago, but reintroduced it later, when I changed the default `main` action in `runmain.js` (this makes it work if main is reexported, and adds more exception handling).

I pushed a fix for the new bug recently, but missed some things required to make it work if `GHCJS_BROWSER` is defined. Should also be fixed now, let me know if you still see it.

**Comment by broma0** [comment]
Still seeing this with a rebuild of ghcjs. 

> git clone https://github.com/ghcjs/ghcjs.git 
> cabal install ./ghcjs
> cd ghcjs
> ghcjs-boot --dev

I'm compiling this code:

> main = error "infinite loop"

With the following command:

> ghcjs -DGHCJS_BROWSER <file>

I've also attempted this in larger project managed with cabal by setting:

> cpp-options: -DGHCJS_BROWSER:

The same issue arises.

I looked around and saw a commit in `ghcjs/shims` that seem to address the issue. Is that the fix you're talking about?

**Comment by luite** [comment]
Yes the fix is in shims. If you're doing a dev build, you can get the latest commits in shims by cleaning first: `ghcjs-boot --dev --clean`. But since there aren't any library changes, you actually don't need to rebuild anything. Just go to `~/.ghcjs/someversion/ghcjs/shims` and `git pull` the latest commits.

**Comment by broma0** [comment]
Confirmed working. Thanks!
