### ISSUE TITLE
truncate on Float gives the wrong answer

### ISSUE THREAD

**Issue by cdsmith** [ghcjs/ghcjs#508]
I am not somewhere I can easily reproduce locally, but here's the problem in CodeWorld:

* https://code.world/haskell#PNtbsmfoyxnnyXbJlaF6EJg

**Comment by cdsmith** [comment]
I did rebuild GHCJS last night with the latest master.tar.gz snapshot, and confirm that this still happens.

**Comment by luite** [comment]
also happens on the `ghc-8.0` branch (and `dedupe`, which doesn't have any changes related to this). will try to fix this at munihac.

**Comment by luite** [comment]
looks like a bug in `decodeFloat_int#`

**Comment by luite** [comment]
I have a fix for this, still running the testsuite to see if it breaks anything

**Comment by luite** [comment]
should be fixed now (`dedupe` and `master` branches, dedupe will be merged into `ghc-8.0` soon)

**Comment by cdsmith** [comment]
I'm still seeing the problem (same link above).  Do you need to build a new master.tar.gz file?

**Comment by cdsmith** [comment]
Just rebuilt from GHCJS HEAD, and I see the fix now. :)
